### ISSUE TITLE
Write the C++ implementation

### ISSUE THREAD

**Issue by shubhangi-singh21** [shubhangi-singh21/My-Codes#2]
Write the C++ implementation for the program moving_avg_from_data_stream.java 
(problem statement explained in moving_avg_from_data_stream.java)

**Comment by MeridjaNassim** [comment]
Can I have this assigned to me, I already have the code implemented.

**Comment by NavyaIyanampudi** [comment]
Can you please assign this to me ?I can code with proper explanation

**Comment by shubhangi-singh21** [comment]
Since @MeridjaNassim asked first, you can go ahead👍 Pls name the file as "moving_avg_from_stream.cpp"

@NavyaIyanampudi you can explore the other issues opened here:)
