### ISSUE TITLE
Add resources in README.md

### ISSUE THREAD

**Issue by shubhangi-singh21** [shubhangi-singh21/My-Codes#8]
You can add resources for:

1. Competitive Programming

2. Data Structures

3. SDE Interview Preparation

**_Read the contribution guidelines carefully before making a PR or contribution. Invalid contributions will not be accepted. Please maintain the consistency of the Resource Pool and work on correct branches_**

**Comment by spacemonkey1101** [comment]
can i contribute?

**Comment by shubhangi-singh21** [comment]
> can i contribute?

@spacemonkey1101 sure!
